In [1]:
import numpy as np
dataset = np.load('sdss_galaxy_colors.npy')
dataset
# We don't require 'spec_class' and 'redshift_err' for our purpose, only columns u, g, r, i, z, redshift are of relevance

array([ (19.84132, 19.52656, 19.46946, 19.17955, 19.10763, b'QSO', 0.539301, 6.543622e-05),
       (19.86318, 18.66298, 17.84272, 17.38978, 17.14313, b'GALAXY', 0.1645703, 1.186625e-05),
       (19.97362, 18.31421, 17.47922, 17.0744, 16.76174, b'GALAXY', 0.04190006, 2.183788e-05),
       ...,
       (19.82667, 18.10038, 17.16133, 16.5796, 16.19755, b'GALAXY', 0.0784592, 2.159406e-05),
       (19.98672, 19.75385, 19.5713, 19.27739, 19.25895, b'QSO', 1.567295, 0.0004505933),
       (18.00024, 17.80957, 17.77302, 17.72663, 17.7264, b'QSO', 0.4749449, 6.203324e-05)], 
      dtype=[('u', '<f8'), ('g', '<f8'), ('r', '<f8'), ('i', '<f8'), ('z', '<f8'), ('spec_class', 'S6'), ('redshift', '<f8'), ('redshift_err', '<f8')])

In [7]:
# MILESTONE 1: Get FEATURES and TARGET for the dataset

def get_features_targets(dataset):
    features = np.zeros((dataset.shape[0], 4))    # n lines, 4 columns, shape parameter has to be an int or sequence of int
    features[:, 0] = dataset['u'] - dataset['g']
    features[:, 1] = dataset['g'] - dataset['r']
    features[:, 2] = dataset['r'] - dataset['i']
    features[:, 3] = dataset['i'] - dataset['z']
    
    targets = dataset['redshift']
    
    return (features, targets)

features, targets = get_features_targets(dataset)
print(features[:5])
print(targets[:5])

[[ 0.31476  0.0571   0.28991  0.07192]
 [ 1.2002   0.82026  0.45294  0.24665]
 [ 1.65941  0.83499  0.40482  0.31266]
 [ 1.5653   0.90174  0.49873  0.38671]
 [ 1.12483  0.65899  0.36996  0.16539]]
[ 0.539301    0.1645703   0.04190006  0.04427702  0.04164413]


In [9]:
#MILESTONE 2: (i) Create a model (ii) Train it (iii) Get some predictions

from sklearn.tree import DecisionTreeRegressor

# Initialise the model
dtr = DecisionTreeRegressor()

# Train the model
dtr.fit(features, targets)

# Make predictions using same features
predictions = dtr.predict(features)

# Print out the first 4 predictions
print(predictions[:4])

[ 0.539301    0.1645703   0.04190006  0.04427702]


In [ ]:

# Function to calculate the median of differences between our predicted and actual values
def median_diff(predicted, actual):
    diff = np.median(np.absolute(predicted - actual))
    return diff

# Function to split the dataset into training and testing features and predictions
